version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: final-project-postgres
    ports:
      - "5434:5432"   # локальный порт 5434 → внутри контейнера 5432
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: final-project
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: final-project-pgadmin
    ports:
      - "8083:80"     # локальный порт 8083 → внутри контейнера 80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  pgdata:
